# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateVectors <- function(nodeColors, edges, directed, weighted, numberOfWeights, fromR = FALSE) {
    .Call('_fibrationSymmetries_calculateVectors', PACKAGE = 'fibrationSymmetries', nodeColors, edges, directed, weighted, numberOfWeights, fromR)
}

getBalancedColoring <- function(nodeColors, colorFixed, edges, directed, weighted, numberOfWeights) {
    .Call('_fibrationSymmetries_getBalancedColoring', PACKAGE = 'fibrationSymmetries', nodeColors, colorFixed, edges, directed, weighted, numberOfWeights)
}

