# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getBalancedColoring <- function(nodeColors, colorFixed, edges, directed, weighted, numberOfWeights) {
    .Call('_fibrationSymmetries_getBalancedColoring', PACKAGE = 'fibrationSymmetries', nodeColors, colorFixed, edges, directed, weighted, numberOfWeights)
}

